### PR TITLE
Agnostic markup for tab title and content

### PR DESCRIPTION
**Pull request by glenveegee**
Currently tabs rely on &lt;h3> and &lt;div> for tab and content respectively. Since &lt;h3> is a semantic element it probably shouldn't be used to mark up the tab. &lt;div> is fine for content.

It would be better to make calculation of tab and tab content agnostic of HTML elements used so that only two siblings (any elements) are necessary. 

I used :first-child and :last-child selectors so that now any two consecutive elements become tab and tab content. This allows for richer markup of actual tabs.

 snapshot1

### CODE REVIEW

**Comment by FrediBach** [comment]
Hi Glen. Sorry for being a bit late on this, but I was in full preparation of my adventure trip for the next two weeks. I had a look at it and will probably add the changes as soon as I'm back.

**Comment by glenveegee** [comment]
No worries Fredi.

Enjoy the trip... sounds exciting. Involve mountains by any chance?

Cheers.

Glen

**Comment by allthosehumans** [comment]
Fredi, you might want to think about taking this even further than what glenveegee mentioned. In CSS more and more of us are making an effort to "decouple" CSS from HTML, meaning that in order to be truly flexible and maintainable we try not to make CSS selectors that rely on any specific HTML elements. You can see this idea in SMACSS, OOCSS, BEM, etc. I believe we should do the same with Javascript. I think jKit has a really bright future. Please consider the idea of using data attributes or classes in order to indicate what HTML elements should be targeted by jKit. I realize it would make implementation a bit less immediate but it will make jKit so much more agnostic and flexible.

**Comment by FrediBach** [comment]
> Fredi, you might want to think about taking this even further than what glenveegee mentioned.

You're right. If I change something on that, it will be something that will go through the whole of jKit. I'm currently thinking about two functions or even included plugins, one to generate a JS object from html structure and one to create html from a compatible JS object. Both functions would take some kind of selector string to define the elements that should be parsed. This would make the whole process of reading data from HTML and generating HTML easier and more flexible.

@glenveegee : Yes, I was "climbing" the Kilimanjaro. Sadly we had way to much wind on the mountain to paraglide down from it. Only one very crazy pilot, Babu from Nepal, actually made a flight, but with a huge level of risk. I'm too old for that kind of stuff. ;-)

**Comment by allthosehumans** [comment]
Fredi, that sounds great. I wish I was good enough with JS to lend you a hand! Put a Paypal button on the jKit site and I'll buy you a beer.

**Comment by FrediBach** [comment]
I was going through quite a few examples and even started to test some implementations about this "issue" and finally decided on how to do it. My idea from above actually got pretty far, but the implementation just never felt right. Than I got a new idea that I actually like it quite a bit. I just call it "Fluid Pattern Detection" for now. Basically it lets jKit guess what you want to do. For example with the tab example that currently needs a structure like this:

```
<div data-jkit="[tabs]">
    <div>
        <h3></h3>
        <div></div>
    </div>
    <div>
        <h3></h3>
        <div></div>
    </div>
</div>
```

I want to make it that it would take anything that follows the same structure, for example:

```
<ul data-jkit="[tabs]">
    <li>
        <h2></h2>
        <p></p>
    </li>
    <li>
        <h2></h2>
        <p></p>
    </li>
</ul>
```

This way jKit will be more flexible with that other stuff you are using jKit with. Let's see how easy it is to implement. :-)

**Comment by FrediBach** [comment]
The first version of this feature is now implemented: http://jquery-jkit.com/community/discussion/34/fluid-pattern-detection

**Comment by allthosehumans** [comment]
Wow Fredi, I'm impressed by how quickly you added this feature! I must admit I still have some doubts about the javascript requiring HTML elements in a certain order and nested in a certain way but I think those concerns are definitely more arguable and less prioritary than removing the dependency on specific HTML tags.

Thanks for the the great work you're doing and for being so responsive!

**Comment by FrediBach** [comment]
> those concerns are definitely more arguable and less prioritary than removing the dependency on specific HTML tags.

Main reason for me to go along this auto detection route was the ease of use for the end user. I'm aware that this kind of detection will always have it's limits, but I don't want to introduce features that maybe only 1% of all jKit users need just to make the life of the other 99% harder in some ways. Same principle for filesize and speed. It's a constant battle of pros and cons where I will always weight ease of use, small filesize and good speed higher than the amount and the flexibility of it's features. I actually was pretty far with the first idea I posted in this thread, but the code was getting bigger and bigger and the API would have been too much for most users anyway.

Anyway, I still have one or two cool ideas how to make this an even better solution for everyone, so stay tuned.

**Pull request closed without merging**
